FROM osrf/ros:noetic-desktop-full

# Install dependencies
RUN apt-get update && DEBIAN_FRONTEND=noninteractive \
	apt-get install -y \
	hdf5-tools \
	libhdf5-dev \
	wget \
	xdg-utils \
	vim \
	git

# Install HDFView
RUN mkdir /usr/share/desktop-directories/ && \
    mkdir /home/Downloads/ && \
    cd /home/Downloads/ && \
    wget https://support.hdfgroup.org/ftp/HDF5/releases/HDF-JAVA/hdfview-3.3.0/bin/HDFView-3.3.0-ubuntu2004_64.tar.gz && \
    tar -xvzf HDFView-3.3.0-ubuntu2004_64.tar.gz && \
    dpkg -i hdfview_3.3.0-1_amd64.deb

# Create a function to call HDFView with silenced output
RUN echo 'HDFView() { /opt/hdfview/bin/HDFView "$1" &> /dev/null; }' >> /root/.bashrc

# Clone event camera driver and checkout specific commit to ensure future consistency
RUN git clone https://github.com/uzh-rpg/rpg_dvs_ros.git && \
    cd /rpg_dvs_ros/ && \
    git checkout 95f08d565c3115b181a4763e1e350f4df0375c4b

# Create catkin workspace
RUN mkdir -p /catkin_ws/src/

# Copy in conversion and image_meta_msgs packages
COPY conversion/ /catkin_ws/src/conversion/
COPY image_meta_msgs/ /catkin_ws/src/image_meta_msgs/

# Add symlink to event message package
RUN ln -s /rpg_dvs_ros/dvs_msgs/ /catkin_ws/src/

# Build conversion package
SHELL ["/bin/bash", "-c"]
RUN source /opt/ros/noetic/setup.bash && \
	cd /catkin_ws && \
    catkin_make

# Source ROS setup.bash script and conversion package on login
RUN echo "source /opt/ros/noetic/setup.bash" >> /root/.bashrc && \
	echo "source /catkin_ws/devel/setup.bash" >> /root/.bashrc
